UglyToad/PdfPig

src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/Content/Letter.cs
src/UglyToad.PdfPig/Content/TextDirection.cs
src/UglyToad.PdfPig/Geometry/PdfRectangle.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Util/DefaultWordExtractor.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

Fix issue with Width, Height and Area when the text orientation is not horizontal.

Fix issue with Width, Height and Area

---

src/UglyToad.PdfPig/DocumentLayoutAnalysis/DocstrumBB.cs
src/UglyToad.PdfPig/DocumentLayoutAnalysis/RecursiveXYCut.cs

Fix wrong order in parameters during the merging operation.

Fix error in DocstrumBB

---

src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/Outline/BookmarkNode.cs
src/UglyToad.PdfPig/Outline/Bookmarks.cs
src/UglyToad.PdfPig/Outline/BookmarksProvider.cs
src/UglyToad.PdfPig/PdfDocument.cs
src/UglyToad.PdfPig/Tokens/NameToken.Constants.cs

Add basic bookmarks extraction capabilities.

---

src/UglyToad.PdfPig.Tests/Geometry/PdfLineTests.cs
src/UglyToad.PdfPig.Tests/Geometry/PdfRectangleTests.cs
src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/Export/PageXmlTextExporter.cs
src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs
src/UglyToad.PdfPig/Geometry/PdfLine.cs
src/UglyToad.PdfPig/Geometry/PdfPath.cs
src/UglyToad.PdfPig/Geometry/PdfPoint.cs
src/UglyToad.PdfPig/Geometry/PdfRectangle.cs

- Implementing `Equals()` and `GetHashCode()` for all paths (here let me know what you think, especially on the Hash)
- PdfPoint:
- MoveXY
- PdfRectangle:
- Contains
- IntersectsWith
- Intersect
- MoveXY
- PdfLine:
- GetBoundingRectangle
- Contains
- IntersectsWith
- Intersect
- ParallelTo
- Line:
- Contains
- IntersectsWith
- Intersect
- ParallelTo
- Bezier Curve:
- Split (see _Computer Aided Geometric Design_ by T. W. Sederberg, section 2.3)
- Intersect
- FindIntersectionT
I've also put some test, but we would need some for the bezier curve

Improving Geometry classes with Tests

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/ReadingOrderDetector/IReadingOrderDetector.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/TextBlock.cs

Make `TextBlock.SetReadingOrder(int)` public so that people can implement their own `IReadingOrderDetector`.

Make TextBlock.SetReadingOrder(int) public

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/ClusteringAlgorithms.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/KdTree.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/DocstrumBoundingBoxes.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/WhitespaceCoverExtractor.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/WordExtractor/NearestNeighbourWordExtractor.cs
src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs

- handle nearest neighbour not found
- handle k-nearest neighbours search
- update DocstrumBB with kd-tree (faster with better results)

K-nearest neighbours search

---

src/UglyToad.PdfPig.Tests/Geometry/PdfPointTests.cs
src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs

- fix minimum area rectangle algo and make it public
- add tests
- tidy up code

Fix minimum area rectangle 

---

src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs

Improve MBR by removing `PdfPoints` creation

Improve Minimum bounding rectangle

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/DuplicateOverlappingTextProcessor.cs
src/UglyToad.PdfPig/Content/Letter.cs

Implement `DuplicateOverlappingTextProcessor`
The downside compared to #185 is that the duplicated letter's font details cannot be updated with `Bold` (`Letter` is internal).
Any comment welcome

Implement DuplicateOverlappingTextProcessor

---

src/UglyToad.PdfPig.Tests/Tokenization/Scanner/PdfTokenScannerTests.cs
src/UglyToad.PdfPig/AcroForms/AcroFormFactory.cs
src/UglyToad.PdfPig/Content/ResourceStore.cs
src/UglyToad.PdfPig/Parser/Parts/DirectObjectFinder.cs
src/UglyToad.PdfPig/PdfExtensions.cs
src/UglyToad.PdfPig/PdfFonts/Parser/Handlers/Type1FontHandler.cs
src/UglyToad.PdfPig/Structure.cs
src/UglyToad.PdfPig/Tokenization/Scanner/IPdfTokenScanner.cs
src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs

Fixes https://github.com/UglyToad/PdfPig/issues/189
I tried to mitigate the breaking change by keep on throwing in most uses of the change method.

FIX : undefined references is a valid use case.

---

src/UglyToad.PdfPig/Geometry/ClippingExtensions.cs
src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs

Add `IntersectsWith(PdfRectangle, PdfLine)` and `Intersect(PdfRectangle, PdfLine)` using clipper

IntersectsWith(rect, line) and Intersect(rect, line)

---

src/UglyToad.PdfPig/Parser/DocumentInformationFactory.cs

Allow to have a metadata stream in the document information entry

---

src/UglyToad.PdfPig.Tests/Dla/DocstrumBoundingBoxesTests.cs
src/UglyToad.PdfPig.Tests/Fonts/SystemFonts/Linux.cs
src/UglyToad.PdfPig.Tests/Parser/Parts/FileHeaderParserTests.cs
src/UglyToad.PdfPig.Tests/TestEnvironment.cs
src/UglyToad.PdfPig.Tests/UglyToad.PdfPig.Tests.csproj

I mainly work on a Mac and some of the unit tests didn't pass due to platform specific issues

Make unit tests behave cross platform

---

src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

I added three functions to draw triangles, circles and ellipsis on pages.

Added graphic functions to PageBuilder

---

src/UglyToad.PdfPig/Content/PageRotationDegrees.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

enables rotating pages
makes builder pattern return the builder instance for fluent invocations

add ability to rotate page by number of degrees, make builder fluent

---

src/UglyToad.PdfPig.Core/PdfRange.cs
src/UglyToad.PdfPig.Tests/Functions/PdfFunctionType0Tests.cs
src/UglyToad.PdfPig.Tests/Functions/PdfFunctionType2Tests.cs
src/UglyToad.PdfPig.Tests/Functions/PdfFunctionType3Tests.cs
src/UglyToad.PdfPig.Tests/Functions/PdfFunctionType4Tests.cs
src/UglyToad.PdfPig.Tests/Functions/Type4/OperatorsTests.cs
src/UglyToad.PdfPig.Tests/Functions/Type4/ParserTests.cs
src/UglyToad.PdfPig.Tests/Functions/Type4/Type4Tester.cs
src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/Content/ResourceStore.cs
src/UglyToad.PdfPig/Functions/PdfFunction.cs
src/UglyToad.PdfPig/Functions/PdfFunctionType0.cs
src/UglyToad.PdfPig/Functions/PdfFunctionType2.cs
src/UglyToad.PdfPig/Functions/PdfFunctionType3.cs
src/UglyToad.PdfPig/Functions/PdfFunctionType4.cs
src/UglyToad.PdfPig/Functions/Type4/ArithmeticOperators.cs
src/UglyToad.PdfPig/Functions/Type4/BitwiseOperators.cs
src/UglyToad.PdfPig/Functions/Type4/ConditionalOperators.cs
src/UglyToad.PdfPig/Functions/Type4/ExecutionContext.cs
src/UglyToad.PdfPig/Functions/Type4/InstructionSequence.cs
src/UglyToad.PdfPig/Functions/Type4/InstructionSequenceBuilder.cs
src/UglyToad.PdfPig/Functions/Type4/Operator.cs
src/UglyToad.PdfPig/Functions/Type4/Operators.cs
src/UglyToad.PdfPig/Functions/Type4/Parser.cs
src/UglyToad.PdfPig/Functions/Type4/RelationalOperators.cs
src/UglyToad.PdfPig/Functions/Type4/StackOperators.cs
src/UglyToad.PdfPig/Graphics/Colors/ColorSpaceDetails.cs
src/UglyToad.PdfPig/Util/ColorSpaceDetailsParser.cs
src/UglyToad.PdfPig/Util/PdfFunctionParser.cs

Implement pdf functions and add type 0, 2 and 4 function tests
<del>I could not find any document with function type 3 example, so no tests so far (PDFBOX only tests type 4). Test for type 0 are basic but could not find any output example. I expect we will be able to test better when rendering to image is implemented </del>
EDIT: I found tests for actual values of type 0 function, now added and fixed the function 0 GetSamples(). bits had to be itereated starting from the end
EDIT 2: I tested function type 3 rendering to image (mainly used in shading it seems)

Implement pdf functions and add type 0, 2 and 4 function tests

---

examples/UglyToad.Examples.csproj
tools/UglyToad.PdfPig.ConsoleRunner/UglyToad.PdfPig.ConsoleRunner.csproj

Might be related to CI issue with C# version

Setting C# version to latest in Examples and ConsoleRunner projects

---

src/UglyToad.PdfPig.Tests/UglyToad.PdfPig.Tests.csproj

Update System.Drawing.Common version in Tests

---

src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs

This pull request comes from the issue: https://github.com/UglyToad/PdfPig/issues/590

CreationDate and ModifiedDate in DocumentInformationBuilder

---

src/UglyToad.PdfPig/Actions/GoToEAction.cs

Fix integration tests for #579 (2)

---

src/UglyToad.PdfPig/Annotations/AppearanceStream.cs
src/UglyToad.PdfPig/Annotations/AppearanceStreamFactory.cs
src/UglyToad.PdfPig/Content/PagesFactory.cs
src/UglyToad.PdfPig/Outline/Destinations/NamedDestinations.cs
src/UglyToad.PdfPig/Outline/Destinations/NamedDestinationsProvider.cs
src/UglyToad.PdfPig/Outline/EmbeddedBookmarkNode.cs

I again ommited some files, I read the errors too quickly. Should hopefully be good now

Fix integration tests for #579 (3)

---

src/UglyToad.PdfPig/Util/PdfFunctionParser.cs

Pass the scanner to get actual value, I forgot that in previous comit

Use IPdfTokenScanner in PdfFunctionType3 create function

---

src/UglyToad.PdfPig/Graphics/Colors/ColorSpaceDetails.cs

Greatly reduces the time to render images with DeviceN and Separation colors spaces. Some DeviceN images take up 15 seconds on my computer (see `ColorSpaceTests.DeviceNColorSpaceImages()` test document). This is reduced to 0.5 second after caching.
(PdfBox does caching too for these 2 color spaces)

Add caching to DeviceN and Separation colors spaces when rendering images

---

src/UglyToad.PdfPig.Fonts/CompactFontFormat/CharStrings/Type2CharStringParser.cs

Implement hflex and hflex1 operators in Type2CharStringParser (fix #558)

---

src/UglyToad.PdfPig.Tests/Graphics/TestOperationContext.cs
src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/Content/IResourceStore.cs
src/UglyToad.PdfPig/Content/ResourceStore.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Parser/PageFactory.cs
src/UglyToad.PdfPig/Parser/PdfDocumentFactory.cs

Make IResourceStore part of the public API and pass InternalParsingOptions to the ResourceStore constructor

---

src/UglyToad.PdfPig/Writer/TokenWriter.cs

guess at issue reported in #743

write null token to output if null encountered #743

---

src/UglyToad.PdfPig.Tests/Fonts/TrueType/Parser/TrueTypeFontParserTests.cs
src/UglyToad.PdfPig.Tests/Integration/VisualVerification/GenerateLetterBoundingBoxImages.cs
src/UglyToad.PdfPig.Tests/UglyToad.PdfPig.Tests.csproj

Let's move out of `System.Drawing` and start using `SkiaSharp` instead

Replace System.Drawing by SkiaSharp in Tests

---

src/UglyToad.PdfPig.Tests/Integration/VisualVerification/GenerateLetterGlyphImages.cs
src/UglyToad.PdfPig.Tests/Integration/VisualVerification/SkiaHelpers/SkiaExtensions.cs
src/UglyToad.PdfPig.Tests/Integration/VisualVerification/SkiaHelpers/SkiaGlyphPageFactory.cs
src/UglyToad.PdfPig.Tests/Integration/VisualVerification/SkiaHelpers/SkiaGlyphStreamProcessor.cs

Add visual verification tests for letter glyphs

---

src/UglyToad.PdfPig.Core/OtherEncodings.cs

Make OtherEncodings Iso88591 readonly

---

src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/Annotations/AnnotationProvider.cs

Make AnnotationProvider public - required to use annotations in `BasePageFactory<T>`

Make AnnotationProvider public

---

src/UglyToad.PdfPig.Core/Globals.cs
src/UglyToad.PdfPig.Core/TransformationMatrix.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Globals.cs
src/UglyToad.PdfPig.Fonts/Globals.cs
src/UglyToad.PdfPig.Tokenization/Globals.cs
src/UglyToad.PdfPig.Tokens/Globals.cs
src/UglyToad.PdfPig/Annotations/QuadPointsQuadrilateral.cs
src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs
src/UglyToad.PdfPig/Globals.cs
src/UglyToad.PdfPig/Images/Png/Adam7.cs
src/UglyToad.PdfPig/Parser/Parts/CrossReference/CrossReferenceStreamParser.cs
src/UglyToad.PdfPig/Writer/NoTextTokenWriter.cs

- Introduce global using statements
- Spanify TransformMatrix.FromArray (eliminating various downstream allocations)
- Optimize Adam7 (eliminate virtual calls and dictionary lookup)
- Replace an interface call in QuadPoints Quadrilateral with direct access to span
- Optimize PdfRectangle.Normalize
- Format TransformMatrix
- Pass TransformMatrix by readonly ref in another case

Improve Code Quality

---

README.md

Fix issues in Advanced Example in README.md

---

src/UglyToad.PdfPig.Tests/Integration/EncryptedDocumentTests.cs
src/UglyToad.PdfPig.Tests/Integration/SpecificTestDocuments/string_encryption_key.pdf
src/UglyToad.PdfPig/Encryption/EncryptionDictionaryFactory.cs

Fix reading encryption byte strings

---

.github/workflows/build_and_test.yml
src/UglyToad.PdfPig.Tests/Tokenization/Scanner/PdfTokenScannerTests.cs
src/UglyToad.PdfPig.Tokens/OperatorToken.cs
src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs

Support relaxed parsing of missing or garbage-prepended endobj/endtream

---

src/UglyToad.PdfPig.Tests/Integration/ColorSpaceTests.cs
src/UglyToad.PdfPig/Images/ColorSpaceDetailsByteConverter.cs

- Support 16 bits per component images
- Added test with result:

Handle unpacking components for 16 bits per component images and use Span in RemoveStridePadding

---

src/UglyToad.PdfPig.Tests/Integration/ColorSpaceTests.cs
src/UglyToad.PdfPig/Graphics/Colors/ColorSpaceDetails.cs

It used to work but code was recently broken. I've added test to make sure this does not happen again
@EliotJones sorry for the numerous PRs, I had time recently (and I cannot approve my own PRs). Let me know if you need help

Fix Separation color space and add tests

---

src/UglyToad.PdfPig.Fonts/TrueType/Parser/TableParser.cs

address #612 since nothing uses this code anyway may as well remove it

remove useless checksum check for truetype font processing

---

src/UglyToad.PdfPig.Core/UglyToad.PdfPig.Core.csproj
src/UglyToad.PdfPig.DocumentLayoutAnalysis/UglyToad.PdfPig.DocumentLayoutAnalysis.csproj
src/UglyToad.PdfPig.Fonts/UglyToad.PdfPig.Fonts.csproj
src/UglyToad.PdfPig.Tokenization/UglyToad.PdfPig.Tokenization.csproj
src/UglyToad.PdfPig.Tokens/UglyToad.PdfPig.Tokens.csproj
src/UglyToad.PdfPig/UglyToad.PdfPig.csproj

Helps with code flagged as `Obsolete`

Stop treating Warnings as Errors

---

src/UglyToad.PdfPig.Fonts/TrueType/Glyphs/Glyph.cs

Fix for IndexOutOfRangeException exception

---

src/UglyToad.PdfPig.Tests/Filters/Ascii85FilterTests.cs
src/UglyToad.PdfPig/Filters/Ascii85Filter.cs
src/UglyToad.PdfPig/Filters/AsciiHexDecodeFilter.cs
src/UglyToad.PdfPig/Filters/RunLengthFilter.cs

Return a copy of the `ArrayPoolBufferWriter` buffer in Ascii85, AsciiHex and RunLength filters and fix #964

Return a copy of the ArrayPoolBufferWriter buffer in Ascii85, AsciiHex and RunLength filters and fix #964

---

src/UglyToad.PdfPig/Images/ColorSpaceDetailsByteConverter.cs

See https://github.com/BobLd/UglyToad.PdfPig.Benchmarks/tree/pull/968 to reproduce

Execute RemoveStridePadding in place when possible

---

src/UglyToad.PdfPig/Images/ColorSpaceDetailsByteConverter.cs

problematic document is the following https://github.com/BobLd/PdfPig.Rendering.Skia/blob/master/UglyToad.PdfPig.Rendering.Skia.Tests/Documents/hex_0x0006.pdf

Update hack for 1bpc + DeviceGray

---

src/UglyToad.PdfPig.Tests/Writer/PdfDocumentBuilderTests.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs

move all arguments to add page to a setting object so it can be extended in future in a non-breaking api change

i merged a pr which broke the build, this updates the build to work

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/DecorationTextBlockClassifier.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/OrderedSet.cs
src/UglyToad.PdfPig/PdfExtensions.cs

Replace usages of List<T>.Contains with a HashSet<T> or OrderedSet<T> as required.

Fix usage of List.Contains

---

src/UglyToad.PdfPig.Tests/Integration/AccentedCharactersInBookmarksTests.cs
src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/Outline/BookmarksProvider.cs
src/UglyToad.PdfPig/Outline/ContainerBookmarkNode.cs
src/UglyToad.PdfPig/Outline/Destinations/ContainerBookmarkNode.cs
src/UglyToad.PdfPig/PdfDocument.cs
src/UglyToad.PdfPig/UglyToad.PdfPig.csproj

pdf specifcation allows a bookmark which has no destination. Some pdf generator such as microsoft msdn will use the feature. I created a container node.

add container node support for BookmarksProvider.cs

---

src/UglyToad.PdfPig.Core/TransformationMatrix.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/TextExtractor/ContentOrderTextExtractor.cs
src/UglyToad.PdfPig.Tests/Dla/UnsupervisedReadingOrderTests.cs
src/UglyToad.PdfPig.Tests/Fonts/SystemFonts/Linux.cs
src/UglyToad.PdfPig.Tests/Integration/IntegrationDocumentTests.cs
src/UglyToad.PdfPig.Tests/Integration/Type0FontTests.cs
src/UglyToad.PdfPig.Tests/Integration/VisualVerification/GenerateLetterBoundingBoxImages.cs
src/UglyToad.PdfPig.Tests/Integration/VisualVerification/GenerateLetterGlyphImages.cs
src/UglyToad.PdfPig/Content/Letter.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/PdfFonts/CidFonts/ICidFont.cs
src/UglyToad.PdfPig/PdfFonts/CidFonts/ICidFontProgram.cs
src/UglyToad.PdfPig/PdfFonts/CidFonts/PdfCidCompactFontFormatFont.cs
src/UglyToad.PdfPig/PdfFonts/CidFonts/PdfCidTrueTypeFont.cs
src/UglyToad.PdfPig/PdfFonts/CidFonts/Type0CidFont.cs
src/UglyToad.PdfPig/PdfFonts/CidFonts/Type2CidFont.cs
src/UglyToad.PdfPig/PdfFonts/Composite/Type0Font.cs
src/UglyToad.PdfPig/PdfFonts/IFont.cs
src/UglyToad.PdfPig/PdfFonts/Simple/TrueTypeSimpleFont.cs
src/UglyToad.PdfPig/PdfFonts/Simple/TrueTypeStandard14FallbackSimpleFont.cs
src/UglyToad.PdfPig/PdfFonts/Simple/Type1FontSimple.cs
src/UglyToad.PdfPig/PdfFonts/Simple/Type1Standard14Font.cs
src/UglyToad.PdfPig/PdfFonts/Simple/Type3Font.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

Fix #1165 
@lihuanglx can you run some tests on your end to check it fits the feature request?
The approach is slightly different than yours, but I believe it achieves the goal

Add GetDescent() and GetAscent() to IFont and loose bounding box to letter
