src/UglyToad.PdfPig.Tests/Tokenization/HexTokenizerTests.cs
src/UglyToad.PdfPig/Tokens/HexToken.cs

This is an attempt at handling the UTF-16 HexToken issue mentioned in #32, by changing the HexToken constructor to look for the UTF16BE BOM at the start of the data and decoding it.
It also adds a couple of unit tests. The change is enough to make those pass, but i'm not sure if any other changes are needed (I know very little about the structure of PDFs).

Add UTF-16 parsing support to HexToken

---

src/UglyToad.PdfPig.Tests/Graphics/TestOperationContext.cs
src/UglyToad.PdfPig/Content/Page.cs
src/UglyToad.PdfPig/Content/PageContent.cs
src/UglyToad.PdfPig/Fonts/CompactFontFormat/CharStrings/Type2BuildCharContext.cs
src/UglyToad.PdfPig/Fonts/Type1/CharStrings/Commands/Type1BuildCharContext.cs
src/UglyToad.PdfPig/Geometry/PdfPath.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Graphics/IOperationContext.cs
src/UglyToad.PdfPig/Graphics/Operations/CloseFillPathEvenOddRuleAndStroke.cs
src/UglyToad.PdfPig/Graphics/Operations/CloseFillPathNonZeroWindingAndStroke.cs
src/UglyToad.PdfPig/Graphics/Operations/FillPathEvenOddRule.cs
src/UglyToad.PdfPig/Graphics/Operations/FillPathEvenOddRuleAndStroke.cs
src/UglyToad.PdfPig/Graphics/Operations/FillPathNonZeroWinding.cs
src/UglyToad.PdfPig/Graphics/Operations/FillPathNonZeroWindingAndStroke.cs
src/UglyToad.PdfPig/Graphics/Operations/FillPathNonZeroWindingCompatibility.cs
src/UglyToad.PdfPig/Graphics/Operations/PathConstruction/AppendRectangle.cs
src/UglyToad.PdfPig/Graphics/Operations/PathConstruction/BeginNewSubpath.cs

Hi, I added Paths collection to Page to be able to get the list of lines/curves on the page. Also added matrix transform to the path operators.

Adding Paths collection

---

src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/DocumentLayoutAnalysis/Docstrum.cs
src/UglyToad.PdfPig/DocumentLayoutAnalysis/TextEdgesExtractor.cs

Text edges are where words have either there BoundingBox's left, right or mid coordinates aligned on the same vertical line. Useful to detect tables, justified text, lists, etc.
Example uf use:
using (PdfDocument document = PdfDocument.Open(path))
{
for (var i = 0; i < document.NumberOfPages; i++)
{
var page = document.GetPage(i + 1);
var words = page.GetWords();
var edges = TextEdgesExtractor.GetEdges(words);
foreach (var edge in edges["left"])
{
// Do something with left edges
}
foreach (var edge in edges["mid"])
{
// Do something with mid edges
}
foreach (var edge in edges["right"])
{
// Do something with right edges
}
}
}
Example of result:
Blue: Left edge
Green: Mid edge (see dotted list)
Pink: Right edge

 Document Layout Analysis - Text edges extractor

---

src/UglyToad.PdfPig.Tests/IO/InputBytesTests.cs
src/UglyToad.PdfPig/IO/StreamInputBytes.cs

When trying to do some tests with 0.0.7 I noticed that some files were failing to open when using the variant of PdfDocument.Open that takes a stream, but were working when using the variant that takes a file path.
Debugging through the code, I think that might be because StreamInputBytes doesn't reset isAtEnd when the stream is seeked away from the end, so once the end has been reached isAtEnd gets left at true permanently.

Change StreamInputBytes.Seek to reset isAtEnd to false

---

src/UglyToad.PdfPig/DocumentLayoutAnalysis/RecursiveXYCut.cs
src/UglyToad.PdfPig/Geometry/PdfRectangle.cs

Adding centroid point to the PdfRectangle. It will useful in layout analysis.

Adding Centroid to PdfRectangle.

---

src/UglyToad.PdfPig/Geometry/PdfPoint.cs

Adding:
- `ToDouble`
- `Equals`
- `GetHashCode`
Not sure if `GetHashCode` is properly done, any feedback welcome.

Improving PdfPoint

---

src/UglyToad.PdfPig/Geometry/PdfPath.cs

__PdfPath__
- Determine if path is closed 
- Determine if path is organised in a __clockwise__ or __counterclockwise__ manner (see accepted answer [here](https://stackoverflow.com/questions/1165647/how-to-determine-if-a-list-of-polygon-points-are-in-clockwise-order) for algo, and see [wiki](https://en.wikipedia.org/wiki/Shoelace_formula)). This is usefull to understand how shapes are filled (using `nonzero` fill rule). NB: it is possible for a closed path to be neither clockwise nor counterclockwise. Hence both `IsClockwise` and `IsCounterClockwise`.
- Add Centroid
__BezierCurve__
- Add `ToLines(int n)` to convert the curve to lines

Improve PdfPath

---

src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoBlock.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoBlockTypeActuate.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoBlockTypeShow.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoEllipse.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoGlyph.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoOcrProcessing.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoPage.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoPositionedElement.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoProcessingStep.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoQuality.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoString.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoTextBlockTextLine.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoTextStyle.cs
src/UglyToad.PdfPig/Export/Alto/AltoDocument.AltoVariant.cs

If you try to deserialise this [alto xml](https://github.com/UglyToad/PdfPig/files/3747790/Random.2.Columns.Lists.Images.1.alto.zip), you will receive the error below as the `xxxSpecified` setters are `private`. Fixing this by switching them to `public`.
`MethodAccessException: Attempt by method 'Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAltoDocument.Read11_AltoDescriptionProcessing(Boolean, Boolean)' to access method 'UglyToad.PdfPig.Export.Alto.AltoDocument+AltoProcessingStep.set_ProcessingCategorySpecified(Boolean)' failed.`

AltoDocument: make all `xxxSpecified` setters public to allow `Deserialize`

---

src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/DocumentLayoutAnalysis/NearestNeighbourWordExtractor .cs
src/UglyToad.PdfPig/Util/DefaultWordExtractor.cs

- Making the code easier to read
- Using 20% of Width instead of 60% for the `maxDistanceFunction`
- Also making `DefaultWordExtractor` public, so that it can be used in the exporters

Enhancing NearestNeighbourWordExtractor

---

src/UglyToad.PdfPig/DocumentLayoutAnalysis/ClusteringAlgorithms.cs
src/UglyToad.PdfPig/DocumentLayoutAnalysis/Distances.cs
src/UglyToad.PdfPig/DocumentLayoutAnalysis/DocstrumBoundingBoxes.cs
src/UglyToad.PdfPig/DocumentLayoutAnalysis/NearestNeighbourWordExtractor .cs

- Changing the `GroupIndexes()` function to use depth first search. The previous implementation was not working properly in some cases.
- Changing the name of `SimpleTransitiveClosure` to `ClusterNearestNeighbours`.
- Changing `FindIndexNearest()` implementation so that it cannot return itsefl.
- Updating `DocstrumBoundingBoxes` by removing the warnings and making the line merging phase (4) more efficient.
More on Depht first search can be found in 'Algorithm design' by Jon Kleinberg and Eva Tardos, on pages 93 and 94. They give a pseudo code and explain its use in grouping (cf. 'Finding the Set of All Connected Components')

Improving clustering algorithm

---

src/UglyToad.PdfPig/DocumentLayoutAnalysis/NearestNeighbourWordExtractor .cs

Removing the font name check (`string.Equals(l1.FontName, l2.FontName, StringComparison.OrdinalIgnoreCase)`) because some special characters or ligatures may belong to different subsets.

Update NearestNeighbourWordExtractor .cs

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/DecorationTextBlockClassifier.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Distances.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/AltoXmlTextExporter.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/HOcrTextExporter.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/PageXmlTextExporter.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/DefaultPageSegmenter.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/DocstrumBoundingBoxes.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/IPageSegmenter.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/RecursiveXYCut.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/XYLeaf.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/XYNode.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/ReadingOrderDetector/DefaultReadingOrderDetector.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/ReadingOrderDetector/IReadingOrderDetector.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/ReadingOrderDetector/RenderingReadingOrderDetector.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/ReadingOrderDetector/UnsupervisedReadingOrderDetector.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/TextBlock.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/TextEdgesExtractor.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/TextLine.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/WhitespaceCoverExtractor.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/WordExtractor/NearestNeighbourWordExtractor.cs

- Tidying the `UglyToad.PdfPig.DocumentLayoutAnalysis` project by creating folders
- Adding `TextBlock.ReadingOrder`
- Adding `IReadingOrderDetector` to gets the blocks in reading order and sets the `TextBlock.ReadingOrder`
- Adding `DefaultReadingOrderDetector` that does nothing
- Adding `RenderingReadingOrderDetector` that retrieve the blocks' reading order using rendering order (TextSequence) as suggested in #61 
- Adding `UnsupervisedReadingOrderDetector` that retrieve the blocks' reading order using both (spatial) Allen’s interval relations and rendering order (TextSequence). __References__: 
- Section 5.1 of _'Unsupervised document structure analysis of digital scientific articles'_ by S. Klampfl, M. Granitzer, K. Jack, R. Kern
- _'Document Understanding for a Broad Class of …

ReadingOrderDetector and tidying DLA project

---

src/UglyToad.PdfPig.Core/TransformationMatrix.cs
src/UglyToad.PdfPig.Tests/Core/TransformationMatrixTests.cs
src/UglyToad.PdfPig/Content/Word.cs
src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs

- Improve bounding box for `Word`. The new method works as follow:
- fit a line through the base line's points to get the slope
- rotate the points to obtain the axis-aligned bounding box (AABB)
- rotate back the AABB to obtain the oriented bounding box (OBB)
__Results:__
In dark (light) red, the old (new) algo:
- Implement the method above in `GeometryExtensions`
- Implement `TransformationMatrix.Inverse()`, needed in the above for the _rotate back_ step. Reference [here](https://en.wikipedia.org/wiki/Invertible_matrix#Inversion_of_3_%C3%97_3_matrices)
The new bounding box approach is inspired by https://arxiv.org/abs/1907.03892, in way much simpler:

Improve bounding box for word

---

src/UglyToad.PdfPig.Tests/Integration/MarkedContentExtractionTests.cs
src/UglyToad.PdfPig/Content/MarkedContentElement.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Graphics/MarkedContentStack.cs

Fix #133 so that `var markedContents = page.GetMarkedContents();` respect the tree structure.

Fix #133 Marked content extraction issue

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/ClusteringAlgorithms.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Distances.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/KdTree.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/DocstrumBoundingBoxes.cs

Implement **kd-tree** data structure to make clustering faster. This will impact both `NearestNeighbourWordExtractor` and `DocstrumBoundingBoxes` classes as they use `ClusteringAlgorithms.ClusterNearestNeighbours(PdfPoint)`.
The kd-tree structure is only used in `ClusteringAlgorithms.ClusterNearestNeighbours(PdfPoint)` for the moment and not in `ClusteringAlgorithms.ClusterNearestNeighbours(PdfLine)`.
See the [wikipedia page](https://en.wikipedia.org/wiki/K-d_tree) for more informations on kd-trees:
- The cost of building the tree in is `O(n log n)` time in the best case. An algorithm that builds a balanced k-d tree to sort points has a worst-case complexity of `O(kn log n)`,
- Finding the nearest point is an `O(log n)` operation on average.
I ran performance tests to compare the current …

Faster clustering with kd-tree

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/WordExtractor/NearestNeighbourWordExtractor.cs

Use Max of `Letter.GlyphRectangle.Width` and `Letter.Width` for both letters (instead of just `GlyphRectangle.Width`).

NearestNeighbourWordExtractor: Improve default max function

---

src/UglyToad.PdfPig.Tests/Writer/PdfMergerTests.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs

`/Pages` Count should reflect the number leaf nodes (page objects) that are descendants of this node. Contrary to what I believe, which was the count Kids object
This is indicated in the [Pdf Specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf):
I added test case too.

Fix an issue where the root `/Pages` Count was incorrect

---

src/UglyToad.PdfPig.Tests/Writer/PdfMergerTests.cs
src/UglyToad.PdfPig.Tokens/ArrayToken.cs
src/UglyToad.PdfPig.Tokens/BooleanToken.cs
src/UglyToad.PdfPig.Tokens/CommentToken.cs
src/UglyToad.PdfPig.Tokens/DictionaryToken.cs
src/UglyToad.PdfPig.Tokens/EndOfLineToken.cs
src/UglyToad.PdfPig.Tokens/HexToken.cs
src/UglyToad.PdfPig.Tokens/IToken.cs
src/UglyToad.PdfPig.Tokens/IndirectReferenceToken.cs
src/UglyToad.PdfPig.Tokens/InlineImageDataToken.cs
src/UglyToad.PdfPig.Tokens/NameToken.cs
src/UglyToad.PdfPig.Tokens/NullToken.cs
src/UglyToad.PdfPig.Tokens/NumericToken.cs
src/UglyToad.PdfPig.Tokens/ObjectToken.cs
src/UglyToad.PdfPig.Tokens/OperatorToken.cs
src/UglyToad.PdfPig.Tokens/StreamToken.cs
src/UglyToad.PdfPig.Tokens/StringToken.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs
src/UglyToad.PdfPig/Writer/PdfStreamWriter.cs

First attempt at trying to lower the binary size of merged document.  The first thing that I did was to 
create a heavy modified version of `UglyToad.PdfPig.Writer.Fonts.BuilderContext` as `UglyToad.PdfPig.Writer.PdfStreamWriter`. This class would be in charge of writing tokens to an arbitrary stream. Token would only be written once, as we push token to the stream, the class would make sure to look for token already written, returning an `IndirectReferenceToken` to it.
When we push token to `PdfStreamWriter`, if this token have a reserved number, it would be immediately pushed to the token list. On the contrary, if the token doesn't have a reserved number the complexity of the insertion would be `O(n) (n being the amount of token that have already being push)`, this is because we have to …

Merger API: Lower object count

---

src/UglyToad.PdfPig.Core/PdfRectangle.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Distances.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/KdTree.cs
src/UglyToad.PdfPig/Content/Word.cs
src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs
src/UglyToad.PdfPig/Parser/PdfDocumentFactory.cs

- Fix `KdTree.FindNearestNeighbours` returning the pivot itself when looking for k nearest neighbours
- Minors clarification doc changes

 Fix KdTree.FindNearestNeighbours(k) returning the pivot itself 

---

src/UglyToad.PdfPig/PdfFonts/Parser/EncodingReader.cs

if baseEncodingObject is a IndirectReferenceToken to a NameToken the previous implementation tried to resolve it as a DictionaryToken, which resultet in an PdfFormatException.

FIX Error when getting Encoding from an IndirectReferenceToken referencing a Name Token

---

src/UglyToad.PdfPig/PdfFonts/Parser/Handlers/Type3FontHandler.cs

I stumbled upon a type 3 font with a name, which seems required in PDF 1.0, according to the spec https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf 
The current code does not take it into account, this PR fixes that.

ADD : name on type 3 fonts

---

src/UglyToad.PdfPig.Fonts/SystemFonts/LinuxSystemFontLister.cs
src/UglyToad.PdfPig.Tests/Fonts/SystemFonts/Linux.cs

- `LinuxSystemFontLister` now checks both '$HOME' and 'HOME' environment variables. It was previously only checking '$HOME' (see [here](https://stackoverflow.com/questions/1143706/getting-the-path-of-the-home-directory-in-c), 'HOME' works on my linux computer);
- It will also check all sub-folders of candidate font folders (fonts are not in the root folder on my linux computer);
- PdfPig will still fail to correctly display the letters of "90 180 270 rotated.pdf" on Linux, as the **TimesNewRomanPSMT** font cannot be found. A check has been added. It work without any problem on windows but fails on linux. Test should be added for mac. **EDIT:** it seems to also fail on MacOs.

fix LinuxSystemFontLister not able to find any font

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/ReadingOrderDetector/UnsupervisedReadingOrderDetector.cs

Allows changing the spatial reasoning rule in use and using or not rendering order.
fix #221

Improve `UnsupervisedReadingOrderDetector` customisation

---

src/UglyToad.PdfPig.Core/PdfSubpath.cs
src/UglyToad.PdfPig.Tests/Graphics/TestOperationContext.cs
src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/BaseDrawingProcessor.cs
src/UglyToad.PdfPig/CrossReference/CrossReferenceTableBuilder.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Graphics/IOperationContext.cs
src/UglyToad.PdfPig/Graphics/Operations/General/SetFlatnessTolerance.cs
src/UglyToad.PdfPig/Graphics/Operations/General/SetLineCap.cs
src/UglyToad.PdfPig/Graphics/Operations/General/SetLineDashPattern.cs
src/UglyToad.PdfPig/Graphics/Operations/General/SetLineJoin.cs
src/UglyToad.PdfPig/Graphics/Operations/General/SetLineWidth.cs
src/UglyToad.PdfPig/Graphics/Operations/General/SetMiterLimit.cs
src/UglyToad.PdfPig/Graphics/Operations/PathConstruction/AppendDualControlPointBezierCurve.cs
src/UglyToad.PdfPig/Graphics/Operations/PathConstruction/AppendEndControlPointBezierCurve.cs
src/UglyToad.PdfPig/Graphics/Operations/PathConstruction/AppendRectangle.cs
src/UglyToad.PdfPig/Graphics/Operations/PathConstruction/AppendStartControlPointBezierCurve.cs
src/UglyToad.PdfPig/Graphics/Operations/PathConstruction/AppendStraightLineSegment.cs
src/UglyToad.PdfPig/Graphics/Operations/PathConstruction/BeginNewSubpath.cs
src/UglyToad.PdfPig/Graphics/Operations/SpecialGraphicsState/ModifyCurrentTransformationMatrix.cs
src/UglyToad.PdfPig/Graphics/Operations/TextPositioning/MoveToNextLine.cs
src/UglyToad.PdfPig/Graphics/Operations/TextState/SetCharacterSpacing.cs
src/UglyToad.PdfPig/Graphics/Operations/TextState/SetFontAndSize.cs
src/UglyToad.PdfPig/Graphics/Operations/TextState/SetHorizontalScaling.cs
src/UglyToad.PdfPig/Graphics/Operations/TextState/SetTextLeading.cs
src/UglyToad.PdfPig/Graphics/Operations/TextState/SetTextRenderingMode.cs
src/UglyToad.PdfPig/Graphics/Operations/TextState/SetTextRise.cs
src/UglyToad.PdfPig/Graphics/Operations/TextState/SetWordSpacing.cs

- remove reference to `TransformationMatrix`, `CurrentGraphicsState`, `PdfPath` and `PdfSubpath` from `IOperationContext` to make it stream processor neutral.
- `IGraphicsStateOperation` are just limited to calling the corresponding operation in `IOperationContext`. `ContentStreamProcessor` takes care of all of that.
Note: `Util.JetBrains.Annotations` is not used anymore in `IOperationContext`. Do we need `[CanBeNull]` in `ContentStreamProcessor`?
This PR should have no impact on the output of document processing/drawing.
This is needed as part of my previous remark:
> - investigate further using a different `IOperationContext` using directly `System.Drawing`'s `Matrix` and `GraphicsPath` (and not using `PdfPig`'s version of these class at all)

Make IOperationContext neutral

---

src/UglyToad.PdfPig/Writer/Copier/IObjectCopier.cs
src/UglyToad.PdfPig/Writer/Copier/MultiCopier.cs
src/UglyToad.PdfPig/Writer/Copier/ObjectCopier.cs
src/UglyToad.PdfPig/Writer/Copier/Page/PagesCopier.cs
src/UglyToad.PdfPig/Writer/Copier/TokenHelper.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs
src/UglyToad.PdfPig/Writer/PdfStreamWriter.cs

I'm introducing a new API that would allow us to track any type of token while is being copied to a stream, so when a similar token come again, we can decide if want to just use the already written token or the new one.
This API would allow to have separated code (`IObjectCopier`) for deduplicating any type of resource, while not penalizing performance, and thus if any `IObjectCopier` it's causing some performance regression that the user don't want, the user could decide not to add it to the main `IObjectCopier` and the resultant pdf would still be valid
This PR is the first part of #193, for easier review.
All the related test pass normally, except **PdfMergerTests::ObjectCountLower**, but it's expected since the writer is not trying to remove duplicated token and I did not include any …

Writer: New API to copy token

---

src/UglyToad.PdfPig.Tests/Fonts/PointSizeTests.cs
src/UglyToad.PdfPig/Content/Letter.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs

- fix `Letter`'s `PointSize` computation by applying the transform to a rectangle of height `fontSize`
- add test with rotated letters
Issue was related to https://stackoverflow.com/questions/48010235/pdf-specification-get-font-size-in-points

Fix Letter's PointSize computation

---

src/UglyToad.PdfPig.Tests/Writer/TokenWriterTests.cs
src/UglyToad.PdfPig/Writer/TokenWriter.cs

Before this fix we were producing a broken binary:
The left document is the original. The right one, is the same document, but the operations of the content stream of that page were written by the library. As you can see operations are being treated as text of the page, rather than operation itself.
Left content stream is from the original document, right content stream come from the document created by the library. As you can see in the we are not properly escaping the special characters. 
The pertinent paragraph in the specifications is:
I didn't find where you were putting the TokenWriter test so I created the file (I didn't search very much either 😢).
Please comment on anything else...
PD: by any chance we can get right of those extra white spaces?

Fix TokenWriter::WriteString not escaping properly special characters

---

src/UglyToad.PdfPig.Tests/Writer/PdfMergerTests.cs
src/UglyToad.PdfPig.Tokens/DictionaryToken.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs

Supersede #245 
This PR offers a much better option and flexible approach to allow a page selection when merging documents. Also, I address the drawback of the other PR which was related to copying pages out of order. As a by product we now allow a page to be copied multiple times (By repeating the page index multiple time in the selection)
Illustration of the problem (Copied)
This is my main document
- Root (Page Tree)
- Tree (Child Page Tree)
- Resources
- Image (F1) (Logo)
- Font (F2) (Custom Font)
- Page (Page No. 1)
- Resources
- Image (F3) (User Icon)
- Page (Page No. 2)
- Resources
- Image (F3) (User Icon)
- Tree (Child Page Tree)
- Resources
- Image (F1) (Another Logo)
- Font (F2) ( Another Custom Font)
- Page (Page No. 3)
- Resources
- Image (F3) (User Icon)
Now, let's try to …

[Improved] PdfMerger: Allow to select the pages when merging documents

---

src/UglyToad.PdfPig.Tests/Fonts/Cmap/CodespaceRangeTests.cs
src/UglyToad.PdfPig/PdfFonts/Parser/Parts/CodespaceRangeParser.cs

Like the commit message say, allow to _parse_ empty code spaces, that way font that have `ToUnicode` dictionary, but no code spaces can be parsed correctly.
PDF Specification related to this problem. I'm in no expert in font, so this may not be the correct fix.

Allow to have empty code space, fixes #256

---

src/UglyToad.PdfPig.Tests/Writer/PdfMergerTests.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs
src/UglyToad.PdfPig/Writer/PdfStreamWriter.cs

Example found on 68-1990-01_A.pdf:
Obj Ref1
Kids [Ref2]
Obj Ref2
Parent Ref1
Let me know if ther is a better/preferred way to handle reference cycles.

fix stackoverflow on pdfmerger

---

src/UglyToad.PdfPig.Tests/Writer/PdfMergerTests.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs
src/UglyToad.PdfPig/Writer/PdfStreamWriter.cs

This pr does two things:
- pdfmerger uses stream instead of byte[]. This should improve performance for large documents/treatments in loop.
- adds an optional output Stream argument on PdfMerger methods. This prevents allocating the newly created documents in memory.

Pdfmerger stream apis

---

src/UglyToad.PdfPig.Tests/Writer/PdfMergerTests.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs

Current implementation uses `IndirectReferenceToken` as the dictionary key which does not override GetHashCode or Equals resulting TryGetValue failing even though matching indirect objects already have been inserted. Modified to use the `IndirectReference` as the key instead and added test coverage to verify indirect objects are not duplicated from same document.

PdfMerger: Fix indirect object lookup dict

---

src/UglyToad.PdfPig.Core/PdfRectangle.cs
src/UglyToad.PdfPig.Tests/Geometry/PdfRectangleTests.cs

fix #261
The problem was that after inverse rotation of the points, some where "outside" the page, leading to negative coordinate.
We now use 1D euclidian distance (Math.Abs())

Use Euclidean distance in PdfRectangle's width and height

---

docs/index.md

Is there a reason https://github.com/UglyToad/PdfPig and https://uglytoad.github.io/PdfPig/ have different readme.md files?

fix broken img source on https://uglytoad.github.io/PdfPig/ 

---

src/UglyToad.PdfPig.Tests/Writer/PdfDocumentBuilderTests.cs
src/UglyToad.PdfPig/Content/Page.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

This is a very naive implementation, because if you copy a lot of pages from a given document you would have duplicated resources. But, I would like to get some thoughts on this implementation.
I was surprise by the amount of code that this feature needed to be implemented. I was expecting a lot more. Even so, there is some duplicated code in two parts:
- [Copying Token](https://github.com/InusualZ/PdfPig/commit/7126564eefbc30c205a165739d333dd6da3ddb0e#diff-a4cfeaa02b17ecfae6639ce457a744a267bf3e7d478740f850a02d0e42cb8c0eR431-R492) This piece of code keep reappearing, I really don't like it.
- [Resource Management](https://github.com/InusualZ/PdfPig/commit/7126564eefbc30c205a165739d333dd6da3ddb0e#diff-ffb8dc0dfd0b8bc578f2ecd4517965154295f4b8900e71ed5948bc2325dd12eeR537-R666) I think this …

[New Feature] PdfPageBuilder: Allow to copy pages from another document

---

src/UglyToad.PdfPig/AcroForms/AcroFormFactory.cs

in the example document in issue #267 the checkbox declares an
appearance state with no corresponding value, as long as the checkbox
defines its appearances dictionary we treat non-off checkboxes as checked
if there is no corresponding value in the checkbox form field dictionary

allow a checkbox to not declare a value and only be checked by appearance #267

---

src/UglyToad.PdfPig/Parser/Parts/DirectObjectFinder.cs

A font was in a streamObject, PdfTokenScanner.ParseObjectStream would return a NullToken (as the object was indeed null)
DirectObjectFinder.Get would then throw on line 79, even thus it should handle null tokens (i.e. ResourceStore.LoadFontDictionary line 152).
I'm unfortunately unable to provide the original pdf, for privacy reasons.
Being able to quickly have a release with this fix would be greatly appreciated 🙏

fixes NullToken for a font

---

src/UglyToad.PdfPig/Writer/WriterUtil.cs

Prevent a nullreference exception when the font in the dictionary is a `NullToken` (valid case).
I'm afraid I am unable to provide a test for this, as I can't share the pdf.

fix null token handling in document creation

---

src/UglyToad.PdfPig/Images/Png/PngFromPdfImageFactory.cs

PngFromPdfImageFactory.TryGenerate erroneously assumes that CMYK images consist of three color components, which makes it determine that the bytesPure array is incorrectly sized.

CMYK has four color components

---

src/UglyToad.PdfPig/PdfFonts/Parser/EncodingReader.cs

Fixes an issue I was having reading a PDF when encodingDictionary is null.
``System.NullReferenceException: Object reference not set to an instance of an object.
at UglyToad.PdfPig.PdfFonts.Parser.EncodingReader.ReadEncodingDictionary(DictionaryToken encodingDictionary, Encoding fontEncoding) in E:\PdfPig\src\UglyToad.PdfPig\PdfFonts\Parser\EncodingReader.cs:line 66``

Fixes null reference exception

---

src/UglyToad.PdfPig/Parser/Parts/DirectObjectFinder.cs
src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs

While testing the library wth a bunch of pdf. I found this "error". The pdf is readable by Adobe Reader and Foxit Reader, although the pdf is not completely compliant since after the `stream` operator contain a space.
So I make the scanner more tolerable to `garbage` after the operator.
The second commit is not related to this problem at all, but it would allow us to see more clearly what token we are reading vs what token we were expecting. QoL

PdfTokenScanner: Fix reading stream operator

---

src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs

An edge case was lost with this commit https://github.com/UglyToad/PdfPig/commit/31ca3640d2c161e3635187bc1bd94158214a6452?branch=31ca3640d2c161e3635187bc1bd94158214a6452&diff=split
when scanner is only followed by \r (without \n)

\r only in token scanner

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/PageXmlTextExporter.cs
src/UglyToad.PdfPig.Tests/Integration/PageXmlTextExporterTests.cs

PageXmlTextExporter: ensure no coords on the page boundaries #399

---

src/UglyToad.PdfPig/Writer/TokenWriter.cs

This should resolve issues (or some of them) from #395.
Existing solution was not properly handling non-Utf16BE string. It would potentially escape some data as if it were non-unicode but then convert to unicode after escaping under certain circumstances. This implementation will properly write out with escaping non-unicode pdf string literals.

adjust string serialization to handle raw byte data properly

---

src/UglyToad.PdfPig.Core/TextRenderingMode.cs
src/UglyToad.PdfPig.Tests/Writer/PdfDocumentBuilderTests.cs
src/UglyToad.PdfPig/Graphics/Core/RenderingModeExtensions.cs
src/UglyToad.PdfPig/Graphics/Operations/TextState/SetTextRenderingMode.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

Adds support for setting the text rendering mode when creating PDFs, as discussed in #368.
The tests are somewhat limited unfortunately, since I don't think there's a way of checking parsed text rendering mode with the current API, it only checks that the text is correctly inserted and can be read again. Is adding rendering mode information to letters  (when parsed) something you'd be interested in?

Add `SetTextRenderingMode` method to `PdfPageBuilder`

---

src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs

Fixed null ref exception in PdfDocumentBuilder that occurs when TokenScanner returns null for the IndirectReferenceToken provided.

Fixed null ref exception in PdfDocumentBuilder

---

.github/workflows/build_and_test.yml
.github/workflows/nightly_release.yml
CONTRIBUTING.md
src/UglyToad.PdfPig.Core/UglyToad.PdfPig.Core.csproj
src/UglyToad.PdfPig.DocumentLayoutAnalysis/UglyToad.PdfPig.DocumentLayoutAnalysis.csproj
src/UglyToad.PdfPig.Fonts/UglyToad.PdfPig.Fonts.csproj
src/UglyToad.PdfPig.Tests/Encryption/AesEncryptionHelperTests.cs
src/UglyToad.PdfPig.Tests/Fonts/SystemFonts/Linux.cs
src/UglyToad.PdfPig.Tests/UglyToad.PdfPig.Tests.csproj
src/UglyToad.PdfPig.Tokenization/UglyToad.PdfPig.Tokenization.csproj
src/UglyToad.PdfPig.Tokens/UglyToad.PdfPig.Tokens.csproj
src/UglyToad.PdfPig/Encryption/AesEncryptionHelper.cs
src/UglyToad.PdfPig/UglyToad.PdfPig.csproj
tools/UglyToad.PdfPig.Package/UglyToad.PdfPig.Package.csproj

#433 includes details of issues when targetting .NET 6, this adds support for .NET 6 by fixing identified breaking changes in the AES API https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams
Adds .NET 6 target framework and runs tests on .NET 6.

Net6 target framework

---

src/UglyToad.PdfPig.Tests/Integration/FarmerMacTests.cs
src/UglyToad.PdfPig.Tests/Integration/Math119FakingDataTests.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Util/Diacritics.cs

Surprisingly PDFs can contain the combining diacritics as part of the content stream. For these combining types combine with the preceding letter since they don't make sense alone. See #439

add handling for combining diacritics #439

---

src/UglyToad.PdfPig.Core/PdfPoint.cs
src/UglyToad.PdfPig.Tests/Geometry/PdfPointTests.cs
src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs

Check if stack has element and invert sorting order in GrahamScan(), add tests
@EliotJones, I've removed references to `net45` and `net451` as I'm not able to compile it locally anymore. Feel free to add the reference back if you want to.

Fix #458 - GrahamScan exception

---

src/UglyToad.PdfPig/Content/PageTreeNode.cs
src/UglyToad.PdfPig/Parser/CatalogFactory.cs
src/UglyToad.PdfPig/Util/EnumerableExtensions.cs

For case when root nod has reference to page the order will be incorrect.
The case if root node has reference
[2 0 R 3 0 R 10 0 R]
Where 2 0 R is intermediate node containing page 1,2,3
Where 3 0 R is intermediate node containing page 4,5,6
Where 10 0 R is page 7
without that fix 7 page will in array as page 1

Fix page number order.

---

src/UglyToad.PdfPig.SystemDrawing/SystemDrawingExtensions.cs
src/UglyToad.PdfPig/BaseDrawingProcessor.cs
src/UglyToad.PdfPig/Graphics/Colors/AlphaColor.cs
src/UglyToad.PdfPig/Graphics/CurrentGraphicsState.cs

Have a pdf document that uses gs operator to change the alpha state of non-stroked graphics to opaque (hidden) so show-text (operator Tj) is not shown  but then writes the text using path operators. The two are in similar places but render differently. 
This change 
1. In BaseDrawngProcessor.cs update SetNamedGraphicsState() to supports the 'ca' and 'CA' tokens in the gs operator to set 
'AlphaConstantStroking' (renamed from just 'AlphaConstant' and a new matching 
'AlphaConstantNonStroking'.
2. Adds a new class AlphaColor (supporting IColor interface) but can wrap any existing color (RGBColor, CMYKColor, GrayColor,...) but add alpha constant (also decimal).
3. In System.Drawing updates SystemDrawingExntions.cs method ToSystemColor() to check for new AlphaColor and return a system color …

Add support for text colors with alpha (aka transparency)

---

src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig/Functions/PdfFunctionType0.cs
src/UglyToad.PdfPig/Functions/Type4/Parser.cs
src/UglyToad.PdfPig/Graphics/IOperationContext.cs
src/UglyToad.PdfPig/Graphics/XObjectContentRecord.cs
src/UglyToad.PdfPig/PdfFonts/CharacterBoundingBox.cs
src/UglyToad.PdfPig/PdfFonts/IFont.cs
src/UglyToad.PdfPig/XObjects/XObjectType.cs

I want to make it easier to review my previous PR https://github.com/UglyToad/PdfPig/pull/555 (that I will drop later on)
This is the first step where we just make some classes public, next step will be to create `BaseStreamProcessor<T>` and update `ContentStreamProcessor` to inherite.
I'm doing that following the latest merge - I want to make sure nothing is lost will doing step 2
(also removing some assert I added in a previous PR)

Make some necessary classes public

---

src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Graphics/CurrentGraphicsState.cs

Update CurrentGraphicsState with `AlphaConstantNonStroking` and `AlphaConstantStroking` and implement more named graphics state
Previous commited in a the `pdf to image rendering` branch by @fnatzke, see https://github.com/UglyToad/PdfPig/pull/515
I've kept the commit small, doing the straightforward named tokens only and not adding `AlphaColor`. `AlphaColor` is not a pdf concept, so it's up for discussion to add it or not in an other PR

AlphaConstants and more named graphics state

---

src/UglyToad.PdfPig/Images/JpegHandler.cs

Simply replaces short with ushort allowing values greater than 32767 to work correctly as it should.
Perhaps renaming ReadShort to ReadUShort is also necessary?

Fixes #567, ReadShort now casts to and returns an ushort

---

src/UglyToad.PdfPig.Tests/PublicApiScannerTests.cs
src/UglyToad.PdfPig.Tests/Writer/PdfDocumentBuilderTests.cs
src/UglyToad.PdfPig/Outline/BookmarksProvider.cs
src/UglyToad.PdfPig/Outline/UriBookmarkNode.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs

- Adds the ability to create and modify outlines of a PDF document through the `PdfDocumentBuilder` interface.
- Adds a new `UriBookmarkNode` type to represent the `URI` action, allow outlines to point to URLs on the web, that supports both read and write.
- Writing `ExternalBookmarkNode` is not implemented because the current interface lacks the required `/D` key that specifies the destination in the external file to jump to, and we don't seem to need the feature.
Fixes https://github.com/UglyToad/PdfPig/issues/156
Once this is shipped, we can switch from `iTextSharp` to `PdfPig`: https://github.com/dotnet/docfx/issues/4250

Support adding outline bookmarks to existing pdf document

---

src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

SMask hardcoded as 8 bitsPerComponent not 1.
Fix for #576,

FixIssue576-AddPng-WithTransparency 

---

src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

Allows adding images to pages with their original size without the need of opening and reading the image width and height again.

Support for full-size images without specifing size

---

src/UglyToad.PdfPig/Graphics/ColorSpaceContext.cs
src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Graphics/IColorSpaceContext.cs

Fix failing integration tests following #595 
https://github.com/UglyToad/PdfPig/actions/runs/4692608923
> 'ColorSpaceContext' does not implement interface member 'IColorSpaceContext.CurrentNonStrokingColorSpace.set'. 'ColorSpaceContext.CurrentNonStrokingColorSpace.set' cannot implicitly implement a non-public member.

Fix integration tests for #595

---

.github/workflows/run_integration_tests.yml

This reverts commit 92f47df9f6c6ff6d01df9dc8815a17e63ca3409d.
@EliotJones should we trigger the run_integration_tests on PR to master too? like the other tests. Would avoid discovering issues after PR has been merged

Revert "Update run_integration_tests.yml"

---

src/UglyToad.PdfPig.Tests/Writer/PdfMergerTests.cs
src/UglyToad.PdfPig/Annotations/AnnotationProvider.cs
src/UglyToad.PdfPig/Content/Page.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs
src/UglyToad.PdfPig/Writer/PdfMerger.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

Implements link copy for PDF merger. 
- Introduces a new `AddPage` overload that takes a `Func<PdfAction, PdfAction> copyLink` parameter to define how links should be copied.
- When `copyLink` is `null` or when `copyLink` returns `null`, links are not copied
- When `copyLink` returns the same instance as input, links are copied as is
- When `copyLink` returns a new instance, links are copied based on the returned instance.
- Update `PdfMerger` to copy links:
- Without page selection, copy all links
- With page selection, copy only links whose target page has been selected.
> NOTE: Named dest links `/Dest` will be turned into goto explicit destination action `/A` after merge
fixes #485 
related: https://github.com/dotnet/docfx/issues/4250

Pdf merger support copy links

---

src/UglyToad.PdfPig.Tests/Functions/Type4/Type4Tester.cs
src/UglyToad.PdfPig/Functions/Type4/InstructionSequenceBuilder.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

When copying multiple pages from a source document to a single destination page, there is a conflict not only with resources prefixed by I (images), but also Fm (containing drawing instructions) and ExtGfxState (used for opacity etc).
This change resolves conflict during page copyFrom.
I introduced a new class to manage name collision (using a default prefix, but that can also fix existing names by extracting the prefix)
The ExtGfxState has to be handled separately since it is referenced in a different operation and is located in a different dictionary.
There are probably other names/resources/instructions that need to be handled in the same way, like ColorSpaces etc...

Fix: copyfrom resources collisions

---

src/UglyToad.PdfPig.Tests/Writer/PdfDocumentBuilderTests.cs
src/UglyToad.PdfPig/Writer/IPdfStreamWriter.cs
src/UglyToad.PdfPig/Writer/ITokenWriter.cs
src/UglyToad.PdfPig/Writer/NoTextTokenWriter.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs
src/UglyToad.PdfPig/Writer/PdfStreamWriter.cs
src/UglyToad.PdfPig/Writer/PdfTextRemover.cs
src/UglyToad.PdfPig/Writer/TokenWriter.cs

Prevents PDF corruption when removing text (PdfTextRemover) by skipping streams that are not (page) content streams or form streams. Also duplicate the original stream's data dictionary, to prevent disappearing elements (due to missing SubType / BBox e.g.)
Added skipping operation MoveToNextLineShowText as well (as suggested by @fnatzke).
This does not solve the array-of-streams / Beads issues mentioned by @fnatzke in issue 538.

Prevent PDF corruption when removing text (#538)

---

src/UglyToad.PdfPig.Fonts/SystemFonts/SystemFontFinder.cs

Allow OS specific ISystemFontFInder implementations for all build targets above and include .NET Standard 2.0, closes #685

Load system fonts in all supported platform builds

---

src/UglyToad.PdfPig.Fonts/CompactFontFormat/Dictionaries/CompactFontFormatTopLevelDictionaryReader.cs
src/UglyToad.PdfPig/AcroForms/AcroFormFactory.cs
src/UglyToad.PdfPig/Graphics/Operations/SpecialGraphicsState/ModifyCurrentTransformationMatrix.cs
src/UglyToad.PdfPig/Graphics/Operations/TextPositioning/SetTextMatrix.cs
src/UglyToad.PdfPig/Util/DictionaryTokenExtensions.cs

Fix exception messages: these showed e.g.
"The cm operator must pass 6 numbers. Instead got: Decimal[]" 
instead of
"The cm operator must pass 6 numbers. Instead got: 4"

Fix exception messages

---

src/UglyToad.PdfPig.Tests/Writer/XmpTests.cs
src/UglyToad.PdfPig/Writer/PdfABaselineRuleBuilder.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs
src/UglyToad.PdfPig/Writer/Xmp/XmpWriter.cs

Add XmpMetadata option to PdfDocumentbuilder as asked in #490 
Can be used as follows:
```csharp
PdfDocumentBuilder pdfDocumentBuilder = new()
{
ArchiveStandard = PdfAStandard.A2A,
IncludeDocumentInformation = true,
XmpMetadata = XDocument.Parse(@"<x:xmpmeta xmlns:x=""adobe:ns:meta/"">
<rdf:RDF xmlns:rdf=""http://www.w3.org/1999/02/22-rdf-syntax-ns#"">
<rdf:Description xmlns:dc=""http://purl.org/dc/elements/1.1/"">
<dc:title>Document title</dc:title>
</rdf:Description>
</rdf:RDF>
</x:xmpmeta>"),
};
```
XMP will only be inserted if a PdfAStandard is chosen. I think this is sufficient for the start.

Add support for custom xmp metadata to PdfDocumentBuilder #490

---

src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs

The `/XYZ` destination needs a zoom value for PDF readers to parse correctly. This PR fixes destination linking problem by adding a NULL zoom value.
Per PDF spec:
> [page /XYZ left top zoom] Display the page designated by page, with the coordinates (left, top) positioned at the top-left corner of the window and the contents of the page magnified by the factor zoom. A null value for any of the parameters left, top, or
zoom specifies that the current value of that parameter is to be retained unchanged. A zoom value of 0 has the same meaning as a null value. 
[#9352](https://github.com/dotnet/docfx/pull/9352)

Fix writing explicit XYZ coordinates

---

src/UglyToad.PdfPig.Fonts/SystemFonts/SystemFontFinder.cs

Fixes a typo in the SystemFontFinder (see #728)
As a side note, the 'SPARC - v9 Architecture Manual' document could be used to add tests as it contains 'Times-BoldItalic'

Fix typo in SystemFontFinder and fix #728

---

src/UglyToad.PdfPig/Encryption/EncryptionHandler.cs

refs #746, #664
There is no indication in the code as to why it explicitly requests the managed AES implementation rather than just using the default, and there are other places in the library that just use ```Aes.Create()```, so this is an attempt at changing it to see if all the tests etc still work.
Also refs https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes.create?view=net-7.0#system-security-cryptography-aes-create(system-string) which says that the version of ```Aes.Create``` that takes a string name has been obsoleted in .NET 7.0

Use the plain Aes.Create() instead of  Aes.Create("AesManaged")

---

src/UglyToad.PdfPig/Images/JpegHandler.cs
src/UglyToad.PdfPig/Images/JpegInformation.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

JPEG files may have 1, 3 or 4 components per pixel. in #710 the image was grayscale but written to the PDF as RGB so the display was all kinds of messed up

#710 set colorspace based on jpeg info

---

src/UglyToad.PdfPig/Writer/TokenWriter.cs

if the string token is in a pdf object then it has pdf doc encoding. in these strings escaping is necessary:
> Within a literal string, the backslash (\) is used as an escape character for various
> purposes, such as to include newline characters, nonprinting ASCII characters,
> unbalanced parentheses, or the backslash character itself in the string. The
> character immediately following the backslash determines its precise
> interpretation (see Table 3.2). If the character following the backslash is not one
> of those shown in the table, the backslash is ignored.
This was the issue in #730. Based on the comments in this code I'm not sure why it was not supported before

handle escaping in pdf doc encoded strings #730

---

src/UglyToad.PdfPig.Fonts/TrueType/Parser/TableParser.cs
src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs

Replace Trade by Debug

---

src/UglyToad.PdfPig.Tests/TestPdfImage.cs
src/UglyToad.PdfPig/Content/IPdfImage.cs
src/UglyToad.PdfPig/Content/InlineImage.cs
src/UglyToad.PdfPig/Graphics/InlineImageBuilder.cs
src/UglyToad.PdfPig/XObjects/XObjectFactory.cs
src/UglyToad.PdfPig/XObjects/XObjectImage.cs

A small PR to use `double` instead of `decimal` in `IPdfImage`'s `Decode` property. It does not change anything as the property is not used (as far as I know) yet. It's just part of the effort to move away from using `decimal`

Use double instead of decimal in IPdfImage's Decode property

---

src/UglyToad.PdfPig.Tests/UglyToad.PdfPig.Tests.csproj

refs #771 - as well as getting some things up to date, also removes quite a few references to old libraries, some of which are lsted as having security issues

Update xunit to 2.6.6

---

src/UglyToad.PdfPig.Tests/UglyToad.PdfPig.Tests.csproj

refs #771
I'm not entirely certain that this will work even though version 17.3.3 still lists older versions of .NET Core as supported TFMs (anything newer requires a newer .NET target in the test project, which is presently still targetting .NET Core 2,0 as well as 6.0)
Anyway - the idea is that it takes out references to a great deal of old libraries - 
with version 16.2.0 of the test SDK:
and with 17.3.3:
including an older version of Newtonsoft.Json which is listed as having security issues (i can't say whether it actually does in this usage)

Retarget the unit test project from .NET Core 2.0 to 2.1, and update the test SDK

---

src/UglyToad.PdfPig.Tests/Fonts/CompactFontFormat/CompactFontFormatParserTests.cs
src/UglyToad.PdfPig.Tests/Fonts/Parser/CMapParserTests.cs
src/UglyToad.PdfPig.Tests/Integration/EmbeddedFileAttachmentTests.cs
src/UglyToad.PdfPig.Tests/Integration/MarkedContentExtractionTests.cs
src/UglyToad.PdfPig.Tests/Integration/OptionalContentTests.cs
src/UglyToad.PdfPig.Tests/Tokenization/ArrayTokenizerTests.cs
src/UglyToad.PdfPig.Tests/Writer/Fonts/Standard14WritingFontTests.cs
src/UglyToad.PdfPig.Tests/Writer/Fonts/ToUnicodeCMapBuilderTests.cs

It seems that the update to xUnit has resulted in a number of analyzer suggestions that are coming out as warnings in the CI build:
So I'm having a go at making the suggested changes to fix the warnings

Fix code analyzer suggestions coming from the updated xUnit packages

---

src/UglyToad.PdfPig/Images/ColorSpaceDetailsByteConverter.cs

Improve performance of the `UnpackComponents()` method. See benchmark below (new method is `OutsideArray`).
(array size is 1.6m bytes and bitsPerComponent set to 1)

Improve UnpackComponents() method performance

---

src/UglyToad.PdfPig/Graphics/Operations/TextShowing/ShowText.cs

Hello, I apologise that I cannot provide the file which led to our discovery of this bug, but I hope that the change is self explanatory enough. A bracket appeared to have migrated inside a string replace operation which was resulting in some commands being corrupted when we re-output content. 
I'm not a regular contributor to any projects on github so I'm not sure if there is a protocol I should have followed, but in the worst case it should be quick enough for someone else to make this change to the main repo :D

Removed mistaken bracket in text replace operation

---

src/UglyToad.PdfPig.Core/PdfDocumentFormatException.cs
src/UglyToad.PdfPig.Core/Polyfills/EncodingExtensions.cs
src/UglyToad.PdfPig.Core/Polyfills/StreamExtensions.cs
src/UglyToad.PdfPig.Fonts/CorruptCompressedDataException.cs
src/UglyToad.PdfPig.Fonts/Polyfills/EncodingExtensions.cs
src/UglyToad.PdfPig.Fonts/Polyfills/StreamExtensions.cs
src/UglyToad.PdfPig.Tokenization/NameTokenizer.cs
src/UglyToad.PdfPig/Content/Page.cs
src/UglyToad.PdfPig/Content/Pages.cs
src/UglyToad.PdfPig/Exceptions/PdfDocumentEncryptedException.cs
src/UglyToad.PdfPig/Graphics/Colors/ColorSpaceDetails.cs
src/UglyToad.PdfPig/Graphics/Operations/OperationWriteHelper.cs
src/UglyToad.PdfPig/IO/StreamWrapper.cs
src/UglyToad.PdfPig/Images/Png/PngStreamWriteHelper.cs
src/UglyToad.PdfPig/PdfDocument.cs
src/UglyToad.PdfPig/Polyfills/NullableAnnotations.cs
src/UglyToad.PdfPig/Polyfills/StreamExtensions.cs
src/UglyToad.PdfPig/Writer/Fonts/ToUnicodeCMapBuilder.cs
src/UglyToad.PdfPig/Writer/PdfStreamWriter.cs
src/UglyToad.PdfPig/Writer/TokenWriter.cs

- Simplifies the pragma statements
- Eliminates a few possible virtual calls
- Avoid encoding in a few more cases where we write known ASCII data

Improve code quality

---

examples/ExtractImages.cs

I tried building this whilst looking at something else, and it failed to compile with an error about ```TryGetBytes``` not existing.
Has it got out of step with the recent spanification changes?

Fix a compile error in the Examples project

---

.github/workflows/build_and_test.yml

Just an attempt to sort these deprecation warnings in the CI builds:

Update Github actions in the CI build

---

tools/UglyToad.PdfPig.Package/UglyToad.PdfPig.Package.csproj

As it stands, the nightly build doesn't have any other deps than System.ValueTuple:
If I try to use that from a brand new / clean .NET Framework 4.7.1 project, I get this error:
So - I think the NuGet package should have a reference to System.Memory on TFMs other than .NET6/8 ?
Edit - Looks like it needs Microsoft.Bcl.HashCode as well

Update the dependencies in UglyToad.PdfPig.Package

---

src/UglyToad.PdfPig.Tests/Tokenization/Scanner/PdfTokenScannerTests.cs
src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs

- Fix of Stream invalid Length issue causing stream data being cut off: fix https://github.com/UglyToad/PdfPig/issues/809
- Improve Stream Token read performance by:
-  simplifying TryReadStream(), avoiding use of MemoryStream, with benefice of already existing Memory Span of "inputBytes"
- removing the unecessary List<>

Improve TryReadStream with simplification & fix of Stream Invalid Length cutting off Streams

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/PageSegmenter/DocstrumBoundingBoxes.cs

As a side note, we should aim not create an array and sort it at all. This is doable as there are only 4 points to compare

Further performance improvements in DocstrumBoundingBoxes

---

src/UglyToad.PdfPig.Core/PdfRectangle.cs
src/UglyToad.PdfPig.Tests/Core/PdfSubpathTests.cs
src/UglyToad.PdfPig.Tests/Dla/DistancesTest.cs
src/UglyToad.PdfPig.Tests/Dla/KdTreeTests.cs
src/UglyToad.PdfPig.Tests/Dla/MathExtensionsTests.cs
src/UglyToad.PdfPig.Tests/Fonts/SystemFonts/Linux.cs
src/UglyToad.PdfPig.Tests/Fonts/TrueType/Parser/TrueTypeFontParserTests.cs
src/UglyToad.PdfPig.Tests/Fonts/Type1/Type1CharStringParserTests.cs
src/UglyToad.PdfPig.Tests/Geometry/BezierCurveTests.cs
src/UglyToad.PdfPig.Tests/Geometry/PdfLineTests.cs
src/UglyToad.PdfPig.Tests/Geometry/PdfPointTests.cs
src/UglyToad.PdfPig.Tests/Geometry/PdfRectangleTests.cs
src/UglyToad.PdfPig.Tests/Geometry/PdfSubpathLineTests.cs
src/UglyToad.PdfPig.Tests/Integration/SinglePageLibreOfficeImages.cs

- Simplify PdfRectangle width and height computation (not sure why I did not use this simple method in the first place)
- Fix DoubleComparer precision in tests (we need to pass the actual precision, not the decimal place)

Simplify PdfRectangle width and height computation and fix tests

---

src/UglyToad.PdfPig/Images/Png/PngFromPdfImageFactory.cs

I don't see any reason why we would not check for that anymore. I missed it while reviewing https://github.com/UglyToad/PdfPig/commit/6d54355754a6778267ad4ba820cd0ceb74473988

Restore checking for correct image size in PngFromPdfImageFactory

---

src/UglyToad.PdfPig.Tests/Tokens/HexTokenTests.cs
src/UglyToad.PdfPig.Tokens/HexToken.cs

Fix parsing of hexadecimal strings with odd number of characters

---

src/UglyToad.PdfPig.Tests/Integration/EncryptedDocumentTests.cs
src/UglyToad.PdfPig.Tests/Integration/SpecificTestDocuments/r4_aes_empty_string.pdf
src/UglyToad.PdfPig/Encryption/AesEncryptionHelper.cs

net80: Support decrypting AES data where only IV is present

---

src/UglyToad.PdfPig.Tests/Parser/Parts/BruteForceSearcherTests.cs
src/UglyToad.PdfPig/Parser/Parts/BruteForceSearcher.cs

Allow rebuilding object offsets when objects do not have endobj token

---

src/UglyToad.PdfPig.Tests/Integration/CatGeneticsTests.cs
src/UglyToad.PdfPig.Tests/Integration/SpecificTestDocuments/pages-indirect-to-null.pdf
src/UglyToad.PdfPig.Tests/Integration/SpecificTestDocuments/pages-kids-not-page.pdf
src/UglyToad.PdfPig/Content/PagesFactory.cs
src/UglyToad.PdfPig/Parser/CatalogFactory.cs

Support not finding the Pages dictionary in lenient mode

---

src/UglyToad.PdfPig.Tests/Parser/Parts/FileStructure/CrossReferenceTableParserTests.cs
src/UglyToad.PdfPig/Parser/FileStructure/CrossReferenceTableParser.cs

Support parsing more cross reference entries than the table count value in lenient mode

---

src/UglyToad.PdfPig/Parser/FileStructure/FileTrailerParser.cs

The logic here can be simplified and we do not need the list anymore

Remove list from FileTrailerParser.GetStartXrefPosition()

---

src/UglyToad.PdfPig.Tests/Integration/GithubIssuesTests.cs
src/UglyToad.PdfPig/Outline/Destinations/ExplicitDestination.cs
src/UglyToad.PdfPig/Outline/Destinations/NamedDestinationsProvider.cs

Default page number to 0 in `ExplicitDestination` when the `Dest` has no page number and fix #736 
NB: `ExplicitDestination.PageNumber` can now be 0.

Default page number to 0 in ExplicitDestination when the Dest has no page number and fix #736

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/AltoXmlTextExporter.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/HOcrTextExporter.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/PageXmlTextExporter.cs
src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/SvgTextExporter.cs
src/UglyToad.PdfPig.Tests/Geometry/ClippingTests.cs
src/UglyToad.PdfPig.Tests/Geometry/PdfPathExtensionsTests.cs
src/UglyToad.PdfPig.Tests/Integration/AnnotationReplyToTests.cs
src/UglyToad.PdfPig.Tests/Integration/AnnotationsTest.cs
src/UglyToad.PdfPig.Tests/Integration/CatGeneticsTests.cs
src/UglyToad.PdfPig.Tests/Integration/ColorSpaceTests.cs
src/UglyToad.PdfPig.Tests/Integration/IntegrationDocumentTests.cs
src/UglyToad.PdfPig.Tests/Integration/OptionalContentTests.cs
src/UglyToad.PdfPig.Tests/Integration/PatternColorTests.cs
src/UglyToad.PdfPig.Tests/Integration/RotationAndCroppingTests.cs
src/UglyToad.PdfPig.Tests/Integration/VisualVerification/GenerateLetterBoundingBoxImages.cs
src/UglyToad.PdfPig.Tests/Writer/PdfDocumentBuilderTests.cs
src/UglyToad.PdfPig.Tests/Writer/PdfMergerTests.cs
src/UglyToad.PdfPig/Content/Page.cs

Move Paths, GetAnnotations() and GetOptionalContents() outside of ExperimentalAccess and mark Experimental class and reference as obsolete
These have been in Experimental Access for long enough

Move Paths, GetAnnotations() and GetOptionalContents() outside of ExperimentalAccess and mark Experimental class and reference as obsolete

---

src/UglyToad.PdfPig.Core/IndirectReference.cs
src/UglyToad.PdfPig/CrossReference/CrossReferenceTable.cs
src/UglyToad.PdfPig/Parser/FileStructure/CrossReferenceObjectOffsetValidator.cs

I've been using PdfPig for text extraction on various files.
Recently, I found 1 file which was taking ~23s to open. Profiling showed that the hotspot was:
```
Dictionary<IndirectReference, long>.TryInsert(...)
at CrossReferenceObjectOffsetValidator.ValidateCrossReferenceOffsets(...)
at CrossReferenceParser.Parse(...)
```
After the changes here, the time to open the document drops to just 3s!

Optimize cross reference object offset validation by avoiding nested loop

---

src/UglyToad.PdfPig.DocumentLayoutAnalysis/TextExtractor/ContentOrderTextExtractor.cs

When parsing PDF files with tables containing multiple lines in a cell or "merged" cells, the separate words can appear out of horizontal order. This option can better predict the spaces between the words.

New GetText() option: NegativeGapAsWhitespace

---

tools/set-version.ps1

The `csproj`s now have only a single `<PropertyGroup>` and it looks like we cannot access them by array index anymore.

Fix "Nightly Release" pipeline following csproj changes

---

src/UglyToad.PdfPig.Tests/Integration/GithubIssuesTests.cs
src/UglyToad.PdfPig/Parser/FileStructure/CrossReferenceParser.cs

Do not throw exception when lenient parsing in ON in CrossReferenceParser and fix #959

Do not throw exception when lenient parsing in ON in CrossReferenceParser and fix #959

---

src/UglyToad.PdfPig/Graphics/Colors/ColorSpaceDetails.cs

Use `Span<>` instead of `ReadOnlySpan<>` in `ColorSpaceDetails`, improve `UnwrapIndexedColorSpaceBytes()` and allow in-place computation when possible

Improve UnwrapIndexedColorSpaceBytes

---

src/UglyToad.PdfPig/Graphics/Colors/ColorSpaceDetails.cs

Make `ColorSpaceDetails.BaseNumberOfColorComponents` public to allow for external image factories

Make ColorSpaceDetails.BaseNumberOfColorComponents public to allow for external image factories

---

src/UglyToad.PdfPig/Content/OptionalContentGroupElement.cs

Add HexToken case in OptionalContent parsing to fix excepition reported here: https://github.com/UglyToad/PdfPig/issues/266#issuecomment-2579540185

Add HexToken case in OptionalContent parsing

---

src/UglyToad.PdfPig.Tests/Graphics/Operations/SpecialGraphicsState/PopTests.cs
src/UglyToad.PdfPig.Tests/Integration/GithubIssuesTests.cs
src/UglyToad.PdfPig.Tests/Integration/SpecificTestDocuments/JD5008.pdf
src/UglyToad.PdfPig/Graphics/BaseStreamProcessor.cs
src/UglyToad.PdfPig/Graphics/Operations/SpecialGraphicsState/Pop.cs

Do not throw error on Pop when stack size is 1 in lenient mode and fix #973

Do not throw error on Pop when stack size is 1 in lenient mode and fix #973

---

src/UglyToad.PdfPig/PdfFonts/Cmap/CMapUtils.cs
src/UglyToad.PdfPig/Util/StackDictionary.cs

Fix warnings about "type 'K' cannot be used as type parameter 'TKey' in the generic type or method 'Dictionary<TKey, TValue>'"

Fix warnings about "type 'K' cannot be used as type parameter 'TKey' in the generic type or method 'Dictionary<TKey, TValue>'"

---

src/UglyToad.PdfPig/Images/ColorSpaceDetailsByteConverter.cs

Update UnpackComponents() to account for 1bpc + DeviceGray (hack for Jbig2)

Update UnpackComponents() to account for 1bpc + DeviceGray (hack for Jbig2)

---

src/UglyToad.PdfPig/PdfExtensions.cs
src/UglyToad.PdfPig/XObjects/XObjectFactory.cs

original implementation from https://github.com/UglyToad/PdfPig/pull/338

Resolve image data (implementation from @kasperdaff)

---

src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs
src/UglyToad.PdfPig/Graphics/PdfPath.cs

Goal is to have public methods to set the `PdfPath` details through `SetStrokeDetails()` and `SetFillDetails()`

Add SetStrokeDetails() and SetFillDetails() to PdfPath and tidy up ContentStreamProcessor

---

.github/workflows/build_and_test_macos.yml
src/UglyToad.PdfPig.Tests/Integration/LetterFilterTests.cs
src/UglyToad.PdfPig.Tests/Writer/PdfDocumentBuilderTests.cs
src/UglyToad.PdfPig/Encryption/AesEncryptionHelper.cs
src/UglyToad.PdfPig/Outline/Destinations/ExplicitDestinationType.cs

Add MacOS test pipeline and fix failing tests
@Greybird I have refactored a bit the `AesEncryptionHelper` class. Please reach out if any issue

Add MacOS test pipeline and fix failing tests

---

src/UglyToad.PdfPig.Core/PdfSubpath.cs

Seal PdfSubpath class and IPathCommand implementations, fix Close.GetHashCode() and fix #1027

Seal PdfSubpath class and IPathCommand implementations, fix Close.GetHashCode() and fix #1027

---

src/UglyToad.PdfPig.Tests/Integration/GithubIssuesTests.cs
src/UglyToad.PdfPig/PdfFonts/CidFonts/PdfCidCompactFontFormatFont.cs
src/UglyToad.PdfPig/PdfFonts/Parser/Parts/CidFontFactory.cs

Handle TrueType case in CidFontFactory where the font is CFF, implement missing members in PdfCidCompactFontFormatFont and fix #554

Handle TrueType case in CidFontFactory where the font is CFF

---

src/UglyToad.PdfPig.Core/IndirectReference.cs
src/UglyToad.PdfPig.Tests/ContentStream/IndirectReferenceTests.cs
src/UglyToad.PdfPig/Parser/FileStructure/CrossReferenceObjectOffsetValidator.cs

Update `IndirectReference` to reflect recent changes in PdfBox implementation, starting from this commit:
https://github.com/apache/pdfbox/commit/0ac944300c806fe64068ce20e680072bdf4ef17b#diff-4b56b6aafe487fe8314f24daa31416e6e578c6779dc60b892e451cc67b002edd
Code change based on 
https://github.com/apache/pdfbox/blob/a53a70db16ea3133994120bcf1e216b9e760c05b/pdfbox/src/main/java/org/apache/pdfbox/cos/COSObjectKey.java#L25

Optimize internal representation of IndirectReference

---

src/UglyToad.PdfPig.Tokens/HexToken.cs
src/UglyToad.PdfPig/Graphics/Operations/TextShowing/MoveToNextLineShowText.cs
src/UglyToad.PdfPig/Graphics/Operations/TextShowing/MoveToNextLineShowTextWithSpacing.cs
src/UglyToad.PdfPig/Graphics/Operations/TextShowing/ShowText.cs
src/UglyToad.PdfPig/Graphics/ReflectionGraphicsStateOperationFactory.cs

- Use ReadOnlyMemory<byte> in ShowText to avoid allocation with ToArray()
- Implement MoveToNextLineShowTextWithSpacing parsing to avoid reflection

Use ReadOnlyMemory<byte> in ShowText operators and implement MoveToNextLineShowTextWithSpacing parsing

---

src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs

when parsing a stream object with multiple `endstream` tokens the last parsed token was selected instead of the actual stream token so instead we just skip all following tokens if the first is a stream and the following tokens are `endstream` operators only
Example file contained something like:
```
12 0 obj
<< /Length 6 >>
stream
123456endstream
endstream
endobj
```
If the length is incorrect the stream parsing is still broken as in #1074 but this fixes the reported bug.

fix #670 by ignoring duplicate endstream definitions

---

src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs

when copying from a ancestor node of a page's resource dictionary we were incorrectly writing nested nodes of e.g. /fonts to the root of the target dictionary, here we write to the intended target node correctly. this is a fix for #936

fix copying of sub-dictionary when keys collide

---

src/UglyToad.PdfPig.Tests/Integration/RotationAndCroppingTests.cs
src/UglyToad.PdfPig/PdfFonts/Simple/Type1Standard14Font.cs

previously every bounding box for type 1 standard 14 fonts was assumed to start at 0,0 and ignored the bounding box data in the font metrics file. now we correctly read the glyph bounding box while preserving the existing advance width values for advancing the renderer position

use correct bounding boxes for standard 14 glyphs #850

---

src/UglyToad.PdfPig.Tests/Images/PngFromPdfImageFactoryTests.cs
src/UglyToad.PdfPig/Content/PdfImageExtensions.cs
src/UglyToad.PdfPig/Graphics/Colors/ColorSpaceDetails.cs
src/UglyToad.PdfPig/Images/Png/PngFromPdfImageFactory.cs
src/UglyToad.PdfPig/Util/ColorSpaceDetailsParser.cs
src/UglyToad.PdfPig/XObjects/XObjectFactory.cs

Remove decode parameter application from Stencil color space for consistency
- Standardise handling of the decode parameter across all color spaces by removing its application in the Stencil color space.
- Previously, only the Stencil color space applied decode inversion, while other color spaces did not.
- This change eliminates confusion when determining which images have already been inverted.

Remove decode parameter application from Stencil color space for consistency

---

src/UglyToad.PdfPig/Writer/PdfContentTransformationReader.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs
src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs

#614 
when adding a page to a builder from an existing document using either addpage or copyfrom methods the added page's content stream can contain a global transform matrix change that will subsequently change all the locations of any modifications made by the user. here whenever using an existing stream we apply the inverse of any active transformation matrix
there could be a bug here where if you use 'copy from' with a global transform active, we then apply the inverse, and you use 'copy from' again to the same destination page our inverse transform is now active and could potentially affect the second stream, but I don't think it will
this code isn't very clean but I think it will be sufficient for now until we can have a bigger refactor of this whole area

when writing content to an existing page inverse any global transform #614

---

src/UglyToad.PdfPig/PdfExtensions.cs

check for cycles during indirect reference resolution

---

src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs

we encountered a fence constructed in the middle of a field for an unknown reason so we demolished it. i think this was intended to catch flaws in the parser logic but the reality is in a pdf anything can happen so we no longer want to catch these issues and this restores a green test run in debug mode.
fix for #915

remove debug asserts causing test failures

---

src/UglyToad.PdfPig.Tests/Graphics/Operations/GraphicsStateOperationTests.cs
src/UglyToad.PdfPig/Graphics/Operations/InlineImages/BeginInlineImageData.cs
src/UglyToad.PdfPig/Graphics/ReflectionGraphicsStateOperationFactory.cs

in order to remove reflection from the core content stream operators construction we ensure all types covered by the operations dictionary have corresponding switch statement support. this moves the remaining 2 operators to the switch statement. fix for #1062
The integration tests will catch anything we missed but according to Gemini this covers all the remaining types.

move last uncovered operators to switch statement

---

src/UglyToad.PdfPig.Tests/Tokenization/NumericTokenizerTests.cs
src/UglyToad.PdfPig.Tokenization/NumericTokenizer.cs

the existing numeric tokenizer involved allocations and string parsing. since the number formats in pdf files are fairly predictable we can improve this substantially
this ends up being somewhere between 2-3 times faster in my benchmarks on a subset of numeric data from PDF files:
```
| Method | Mean      | Error     | StdDev    |
|------- |----------:|----------:|----------:|
| PigOld | 13.684 us | 0.2333 us | 0.2182 us |
| PigNew |  5.963 us | 0.0990 us | 0.0877 us |
| Method | Mean      | Error     | StdDev    |
|------- |----------:|----------:|----------:|
| PigOld | 14.806 us | 0.2098 us | 0.1962 us |
| PigNew |  6.230 us | 0.1205 us | 0.1127 us |
```
Based on tracing for opening ~350 documents the tokenize method here was called approximately 16.2 million times so is definitely a …

rework numeric tokenizer hot path

---

src/UglyToad.PdfPig.Tokens/NameToken.Constants.cs
src/UglyToad.PdfPig/Writer/PdfDocumentBuilder.cs

in #1082 and other issues relating to annotations we're running into constraints of the current model of building a pdf document. currently we skip all link type annotations, i think we can support copying of links where the link destination is outside the current document. however the more i look at this code the more i think we need a radical redesign of how document building is done because it has been pushed far beyond its current capabilities, i'll detail my thinking in the related pr in more detail

make link copying more tolerant when adding page

---

src/UglyToad.PdfPig.Fonts/CompactFontFormat/Charsets/CompactFontFormatCharset.cs
src/UglyToad.PdfPig/PdfFonts/FontFactory.cs

- a file contained 2 indices pointing to '.notdef' for the character name so we just take the first rather than requiring a single
- a file contained '/' (empty name) as the subtype declaration, so we fall back to trying type 1 and truetype parsing in this situation
with these changes we can now parse the 6000 files from `0000` to `0005` in the corpus with the exception of corrupt files and files with corrupt xrefs which we can't currently recover from but are possible to parse in some readers:
- 0005634.pdf
- 0002973.pdf
https://digitalcorpora.s3.amazonaws.com/s3_browser.html#corpora/files/CC-MAIN-2021-31-PDF-UNTRUNCATED/zipfiles/0000-0999/

handle additional broken pdf files in the common crawl set

---

README.md

we need to be more clear because beloved chat gpt falls into the trap of recommending `page.Text` when asked about the library even though this text is usually the wrong field to use

update readme to avoid people using `page.Text` or asking about editing docs

---

src/UglyToad.PdfPig.Core/ArrayPoolBufferWriter.cs
src/UglyToad.PdfPig.Core/IndirectReference.cs
src/UglyToad.PdfPig.Core/OtherEncodings.cs
src/UglyToad.PdfPig.Core/PdfDocEncoding.cs
src/UglyToad.PdfPig.Core/PdfLine.cs
src/UglyToad.PdfPig.Core/PdfPoint.cs
src/UglyToad.PdfPig.Core/PdfRectangle.cs
src/UglyToad.PdfPig.Core/PdfSubpath.cs
src/UglyToad.PdfPig.Core/TransformationMatrix.cs
src/UglyToad.PdfPig.Core/UglyToad.PdfPig.Core.csproj
src/UglyToad.PdfPig.Core/Union.cs

Make `UglyToad.PdfPig.Core` support nullability. The change to `Union<A, B>` seems wrong to me but we have until 0.1.12 to fix this

add nullability to core project

---

src/UglyToad.PdfPig.Tests/Tokenization/Scanner/CoreTokenScannerTests.cs
src/UglyToad.PdfPig/Parser/CatalogFactory.cs

as long as there is a pages entry we accept this in lenient parsing mode. this is to fix document 006705.pdf in the corpus that had '/calalog' as the dictionary entry.
also adds a test for some weird content stream content in 0006324.pdf where numbers seem to get split in the content stream on a decimal place. this is just to check that our parser doesn't hard crash

allow missing catalog type definition for catalog dictionary

---

src/UglyToad.PdfPig/Parser/PdfDocumentFactory.cs

address part of #1146
`stream.Position` needs `CanSeek` (see https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.position?view=net-9.0)
We just create the `StreamInputBytes` before accessing the Position

First create the StreamInputBytes in PdfDocument.Open() to check the stream CanRead and CanSeek

---

src/UglyToad.PdfPig.Tests/Parser/0007511-page-2.txt
src/UglyToad.PdfPig.Tests/Parser/PageContentParserTests.cs
src/UglyToad.PdfPig.Tests/UglyToad.PdfPig.Tests.csproj
src/UglyToad.PdfPig.Tokenization/Scanner/CoreTokenScanner.cs

this file cotains corrupt content following an inline image but other parsers just treat this content as part of the image and parse the rest of the file successfully

copy other parser behavior by treating end of stream as valid end inline image

---

src/UglyToad.PdfPig/Content/ResourceStore.cs

in document 10122 the font and xobject names are the same so the xobject overwrote references to the font for the page content, separate the dictionaries

handle case where xobjects use same key as fonts
